"""Add category field to Habit

Revision ID: 366fe629b7cd
Revises: a875e636f1d3
Create Date: 2026-02-11 20:33:27.985012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366fe629b7cd'
down_revision = 'a875e636f1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
