"""Initial migration with all current tables

Revision ID: a875e636f1d3
Revises: 
Create Date: 2026-02-11 20:07:59.068039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a875e636f1d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('occurrences', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_adherence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('frequency')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('active')
        batch_op.drop_column('target_adherence')
        batch_op.drop_column('occurrences')
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
